version: '3.1'

services:

  cur_dir:
    build: .
    restart: always
    ports:
    - "0.0.0.0:8443:8443"

  rediska:
    image: redis
    user: root
    ports:
    - "127.0.0.1:6379:6379"

  db:
    image: mariadb
    restart: always
    ports:
      - "127.0.0.1:8083:3306"
    volumes:
      - ./database_on_local:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root

